models/connection.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

models/model.py
from models.connection import db
from flask_bcrypt import Bcrypt 
from flask_login import UserMixin

bcrypt = Bcrypt() 

class QrData(db.Model):
    id = db.Column(db.Integer,unique=True, primary_key=True)
    name = db.Column(db.String(120), unique=True, nullable=False)
    link = db.Column(db.String(120), unique=False, nullable=False)
    color = db.Column(db.String(10), unique=False, nullable=False)
    back = db.Column(db.String(10), unique=False, nullable=False)
    filename = db.Column(db.String(120), unique=False, nullable=False)


class QrUser(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128)) 

    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash (password).decode('utf-8') 

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'

app.py
import os
from flask import Flask, redirect, request, url_for 
from flask_migrate import Migrate
from models.model import *
from models.connection import db
from dotenv import load_dotenv
from flask_qrcode import QRcode
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from routes.auth import auth as bp_auth
from routes.qr import qrcode as bp_qr
from flask_login import LoginManager


app = Flask(__name__)
app.register_blueprint(bp_auth, url_prefix='/')
app.register_blueprint(bp_qr, url_prefix='/QR')
load_dotenv()
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('SQLALCHEMY_DATABASE_URI')
app.config['UPLOAD_FOLDER'] = 'static/'

db.init_app(app)

migrate = Migrate(app, db)
QRcode(app)

class ProtectedModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('auth.login', next=request.url))
    
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    stmt = db.select(QrUser).filter_by(id=user_id)
    user = db.session.execute(stmt).scalar_one_or_none()
    return user

@app.route('/')
def home():
    return redirect(url_for('auth.login'))

if __name__ == '__main__':
    app.run(debug=True)

routes/auth.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask import current_app   # definisce il contesto del modulo
from flask_login import login_user  # https://flask-login.readthedocs.io/en/latest/#flask_login.login_user
from flask_login import login_required
from flask_login import current_user
from flask_login import logout_user



from models.connection import db
from models.model import *

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    # shows the login form page
    return render_template('auth/login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    # manages the login form post request
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = QrUser.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not user.check_password(password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('qr.history'))    


@auth.route('/logout')
@login_required
def logout():
    logout_user()  # https://flask-login.readthedocs.io/en/latest/#flask_login.logout_user

    return render_template('auth/login.html')


@auth.route('/signup')
def signup():
    # shows the login form page
    return render_template('auth/signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    # signup input validation and logic
    #TODO verify password strenght
    username = request.form["username"] #as an alternative use request.form.get("username")
    email = request.form["email"]    
    password = request.form["password"]

    if not username:
        flash('Invalid username')
        return redirect(url_for('auth.signup'))
    if not email:
        flash('Invalid email')
        return redirect(url_for('auth.signup'))
    if not password:
        flash('Invalid password')
        return redirect(url_for('auth.signup'))                
    
    user = QrUser.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database
    if user: 
        # if a user is found, we want to redirect back to signup page so user can try again
        # display some kind of error
        flash('User with this email address already exists')
        return redirect(url_for('auth.signup'))

    user = QrUser(username=username, email=email)
    user.set_password(password)  # Imposta la password criptata
    db.session.add(user)  # equivalente a INSERT
    db.session.commit()

    return redirect(url_for('auth.login'))

def signup_post():
    return 'signup_post'

routes/qr.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import current_app
from werkzeug.utils import secure_filename

import os

from models.connection import db
from models.model import *


qrcode = Blueprint('qr', __name__)


ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

@qrcode.route('/qr')
def qr():
     return render_template('QR/create_qr.html')

@qrcode.route('/generate_qr/',methods=['POST'])
def generate_qr():  
    name = request.form["name"]
    url = request.form["url"]
    color = request.form["color"]
    back = request.form["backcolor"]
    file = request.files['icon_img']
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
    save_qr_data(name=name,url=url, color=color, back=back,file=filename)
    return render_template('QR/qr_result.html', url=url, color=color, back=back, file=filename)


def save_qr_data(name, url, color, back, file):
    qr = QrData(name=name, link=url, color=color, back=back, filename=file)
    db.session.add(qr)  # equivalente a INSERT
    db.session.commit() 
    return f"Qr per il seguente link creato con successo: {qr.link}"

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@qrcode.route('/history')
def history():
    qrcodes = QrData.query.all()
    return render_template('QR/qr_history.html', qrcodes=qrcodes)

templates/QR/create_qr.html
<!-- auth\login.html -->
{% extends "qr_base.html" %}

{% block title %}Crea il tuo QR{% endblock %}



{% block content %}

<h1>Personalizza il tuo QR</h1>

<div class="row">
    <div class="col">
        <form method="POST" action="generate_qr" enctype=multipart/form-data>
            <br>
            <div class="mb-3"></div>
            <h3>Inserisci un nome:</h3>
            <input class="form-control" type="text" name="name" placeholder="Inserisci un nome per il tuo QR">
    </div>
    <br>

    <div class="mb-3">
        <h3>Link:</h3>
        <input class="form-control" type="text" name="url" placeholder="Inserisci il link del tuo QR">
    </div>
    <br>

    <h3>Colore di sfondo:</h3>

    <div class="col-1">
        <input class="form-control" type="color" name="backcolor" id="backcolor" value="#FFFFFF">
    </div>



    <h3>Colore del QR:</h3>

    <div class="col-1">
        <input class="form-control" type="color" name="color" id="color">
    </div>
    <br>
    <br>

    <label for="avatar">Scegli una foto da inserire nel QR:</label>

    <input type="file" id="icon_img" name="icon_img" accept="image/png, image/jpeg" />

    <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>
</div>
{% endblock %}

templates/QR/qr_history.html
{% extends "qr_base.html" %}

{% block content %}
    {% for qr in qrcodes %}
        <div class="row my-3">
            <div class="col-md-8">
                <div class="card" style="min-width: 12rem; max-width: 25rem;">
                    <div class="card-header text-center">
                        <strong>{{ qr.name }}</strong>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>URL:</strong> {{ qr.link }}</li>
                        <li class="list-group-item"><strong>Fill Color:</strong> {{ qr.color }}</li>
                        <li class="list-group-item"><strong>Background Color:</strong> {{ qr.back }}</li>
                        <li class="list-group-item"><strong>Icon Image:</strong> {{ qr.filename }}</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 d-flex align-items-center justify-content-center">
                <img src="{{ qrcode(qr.url, fill_color=qr.color, back_color=qr.back, error_correction='H', icon_img=qr.filename) }}" style="max-width: 100%; height: auto;" alt="QR Code">
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/QR/qr_result.html
{% extends "qr_base.html" %}

{% block title %}QR generator{% endblock %}

{% block content %}

    <center>    
        <h1 class="text-success p-5">Scan your QR code!</h1>
        <img src="{{ qrcode(url,fill_color=color, back_color=back, error_correction='H', icon_img=file) }}" style="height: 20%;">
        <div class="card" style="width: 18rem;">
            <div class="card-header text-center">
                <strong>{{ name }}</strong>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>URL:</strong> {{ url }}</li>
                <li class="list-group-item"><strong>Fill Color:</strong> {{ color }}</li>
                <li class="list-group-item"><strong>Background Color:</strong> {{ back }}</li>
                <li class="list-group-item"><strong>Icon Image:</strong> {{ file }}</li>
            </ul>
        </div>
    </center>

{% endblock %}

templates/qr_base.html
<!DOCTYPE html>
<!-- base.html -->
<html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<head>
  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if not current_user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('qr.qr') }}">Genera QR</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('qr.history') }}">History</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
          {% endif %}
        </ul>

        {% if current_user.is_authenticated %}
        <span class="navbar-text">
          {{ current_user.username }}
        </span>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
    <!-- Content here -->
    {% block content %}{% endblock %}
  </div>
</body>

</html>